# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_recognition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17image_recognition.proto\x12\x11image_recognition\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1f\n\rImageResponse\x12\x0e\n\x06labels\x18\x01 \x03(\t2c\n\x11ImageLabelService\x12N\n\tGetLabels\x12\x1f.image_recognition.ImageRequest\x1a .image_recognition.ImageResponseB\x12Z\x10go_service/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_recognition_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\020go_service/proto'
  _IMAGEREQUEST._serialized_start=46
  _IMAGEREQUEST._serialized_end=80
  _IMAGERESPONSE._serialized_start=82
  _IMAGERESPONSE._serialized_end=113
  _IMAGELABELSERVICE._serialized_start=115
  _IMAGELABELSERVICE._serialized_end=214
# @@protoc_insertion_point(module_scope)
